# Generated by Django 3.0.1 on 2020-07-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidosaida',
            options={'verbose_name': 'pedido saída', 'verbose_name_plural': 'pedido saída'},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='produtos',
        ),
    ]
